repair:
  single-delay-seconds: 10
  full-delay-seconds: 86400
  cost:
    coins: 10
    obols: 5
    gems: 1

steal-coins:
  allowed-worlds:
    - worldname
  other-percent-of-coins: 5
  personal-percent-of-coins: 10
  seconds-last-hit: 30