name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresonsomnium.${project.artifactId}
api-version: "1.16"
author: Areson
commands:
  somniumadmin:
    description: "AresonSomnium admin command"
    permission: aresonsomnium.admin
    usage: /somniumadmin <function> [args...]
  somniumtest:
    description: "AresonSomnium testing command"
    permission: aresonsomnium.admin
    usage: /somniumtest <function> [args...]
  opengui:
    description: "Open a GUI"
    permission: aresonsomnium.player
    usage: /opengui <guiName>
    aliases: [shop]
  stats:
    description: "See your stats"
    permission: aresonsomnium.player
    usage: /stats
    aliases: [ statistiche ]

depend:
  - Essentials

permissions:
  aresonsomnium.admin:
    default: op
  aresonsomnium.player:
    default: true