name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.aresonsomnium.${project.artifactId}
api-version: "1.16"
author: Areson
commands:
  somniumadmin:
    description: "AresonSomnium admin command"
    permission: aresonsomnium.admin
    usage: /<command> <function> [args...]
  somniumtest:
    description: "AresonSomnium testing command"
    permission: aresonsomnium.admin
    usage: /<command> <function> [args...]

permissions:
  aresonsomnium.admin:
    default: op