name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
api-version: 1.18
author: Areson
depend:
  - CommandPanels
  - Essentials
  - LuckPerms
  - PlaceholderAPI

commands:
  somniumsinglefreerepair:
    description: "Single free repair command"
    permission: aresonsomnium.admin
  somniumsinglerepair:
    description: "Single repair command"
    permission: aresonsomnium.admin
  somniumfullrepair:
    description: "Full repair command"
    permission: aresonsomnium.admin
  shopadmin:
    description: "Shop admin command"
    permission: aresonsomnium.admin
  somniumadmin:
    description: "AresonSomnium admin command"
    permission: aresonsomnium.admin
    usage: /somniumadmin <function> [args...]
  gomma:
    description: "AresonSomnium gomma command"
    permission: aresonsomnium.admin
    usage: /gomma <function>
  somniumtest:
    description: "AresonSomnium testing command"
    permission: aresonsomnium.admin
    usage: /somniumtest <function> [args...]
  opengui:
    description: "Open a GUI"
    permission: aresonsomnium.admin
    usage: /opengui <guiName>
    aliases: [ shop ]
  obols:
    description: "Obols commands"
    permission: aresonsomnium.admin
    usage: /obols <guiName>
  stats:
    description: "See your stats"
    permission: aresonsomnium.player
    usage: /stats
    aliases: [ statistiche ]
  assegno:
    description: "Crea un assegno"
    permission: aresonsomnium.player
    usage: /assegno <amount>
    aliases: [ buono ]
  sellall:
    description: "Sell all items in inventory"
    permission: aresonsomnium.player
    usage: /sellall
  sellhand:
    description: "Sell the item in main hand"
    permission: aresonsomnium.player
    usage: /sellhand
  autosell:
    description: "Autosell items in inventory"
    usage: /autosell
  giveConsumable:
    description: "Give a consumable object"
    permission: aresonsomnium.admin
    usage: /giveConsumable
  riassunto:
    permission: aresonsomnium.player

permissions:
  aresonsomnium.admin:
    default: op
  aresonsomnium.player:
    default: true
